import type { Language } from '../domain'

export type TranslationKey =
  | 'nav.home' | 'nav.explore' | 'nav.groups' | 'nav.profile' | 'nav.settings'
  | 'shell.yourSpace' | 'shell.playModes' | 'shell.classic' | 'shell.sideSwitch' | 'shell.personChallenge' | 'shell.teamDebate' | 'shell.new' | 'shell.privateByDefault' | 'shell.keepStreak' | 'shell.startStreak' | 'shell.streakBody' | 'shell.freshBuild' | 'shell.updateReady' | 'shell.privacy' | 'shell.betaTerms' | 'shell.communityRules' | 'shell.deleteData' | 'shell.switchLanguage' | 'shell.help' | 'shell.notifications' | 'shell.noNotifications' | 'shell.helpMessage' | 'shell.chooseMode'
  | 'common.back' | 'common.close' | 'common.cancel' | 'common.save' | 'common.saving' | 'common.loading' | 'common.retry' | 'common.startDebate' | 'common.takeASide' | 'common.viewAll' | 'common.viewProfile' | 'common.editProfile' | 'common.settings' | 'common.searchTakes' | 'common.today' | 'common.global' | 'common.private' | 'common.privateByDefault' | 'common.continue' | 'common.copy' | 'common.join' | 'common.create' | 'common.debate' | 'common.startThisTake' | 'common.anotherTake' | 'common.editInterests' | 'common.sendFeedback' | 'common.sending' | 'common.optional' | 'common.offline'
  | 'home.eyebrow' | 'home.greetingMorning' | 'home.greetingAfternoon' | 'home.greetingEvening' | 'home.valueStatement' | 'home.challengePerson' | 'home.worldTake' | 'home.dailyQuestion' | 'home.fiveMinutesPrivate' | 'home.dailySignal' | 'home.signalDetails' | 'home.splitRoom' | 'home.splitRoomBody' | 'home.seeRoom' | 'home.personalized' | 'home.yourTake' | 'home.keepMoving' | 'home.recentShifts' | 'home.inProgress' | 'home.continueDebate' | 'home.draftSaved' | 'home.latestResult' | 'home.argumentScore' | 'home.startExploring' | 'home.findDisagreement' | 'home.browseTakes' | 'home.categories' | 'home.firstShift' | 'home.firstShiftBody' | 'home.debatesCompleted' | 'home.averageScore' | 'home.editInterests'
  | 'take.category' | 'take.minutes' | 'take.start' | 'take.difficulty.easy' | 'take.difficulty.medium' | 'take.difficulty.hard' | 'take.sourceEnglish'
  | 'explore.eyebrow' | 'explore.title' | 'explore.body' | 'explore.allTopics' | 'explore.balanced' | 'explore.inTopic' | 'explore.nextTake' | 'explore.keepPrivate' | 'explore.keepCurious' | 'explore.privateBody' | 'explore.libraryEmpty'
  | 'debateChoice.eyebrow' | 'debateChoice.title' | 'debateChoice.body' | 'debateChoice.aiEyebrow' | 'debateChoice.aiTitle' | 'debateChoice.aiBody' | 'debateChoice.aiAction' | 'debateChoice.personEyebrow' | 'debateChoice.personTitle' | 'debateChoice.personBody' | 'debateChoice.personAction' | 'debateChoice.teamEyebrow' | 'debateChoice.teamTitle' | 'debateChoice.teamBody' | 'debateChoice.teamAction' | 'debateChoice.privacy'
  | 'onboarding.privateByDefault' | 'onboarding.eyebrow' | 'onboarding.title' | 'onboarding.body' | 'onboarding.setup' | 'onboarding.callYou' | 'onboarding.profilePrivate' | 'onboarding.displayName' | 'onboarding.yourName' | 'onboarding.arenas' | 'onboarding.chooseThree' | 'onboarding.enter' | 'onboarding.stancePrivate' | 'onboarding.offline' | 'onboarding.nameTooShort' | 'onboarding.interestsTooFew' | 'onboarding.saveError'
  | 'profile.eyebrow' | 'profile.keepQuestions' | 'profile.privateBody' | 'profile.debateDna' | 'profile.averageScore' | 'profile.strongest' | 'profile.currentStreak' | 'profile.categories' | 'profile.latestSignal' | 'profile.bestStreak' | 'profile.sideSwitch' | 'profile.classic' | 'profile.challengeResponses' | 'profile.challengesCreated' | 'profile.history' | 'profile.activeDays' | 'profile.noDebates' | 'profile.firstResult' | 'profile.privateDefault' | 'profile.aiDisclaimer'
  | 'settings.eyebrow' | 'settings.title' | 'settings.body' | 'settings.account' | 'settings.appearance' | 'settings.preferences' | 'settings.contentBody' | 'settings.interfaceLanguage' | 'settings.debateLanguage' | 'settings.intensity' | 'settings.defaultMode' | 'settings.aiStyle' | 'settings.presetAvatar' | 'settings.shortBio' | 'settings.bioPlaceholder' | 'settings.bioHelp' | 'settings.theme' | 'settings.textSize' | 'settings.accent' | 'settings.reduceMotion' | 'settings.reduceMotionHelp' | 'settings.privacyData' | 'settings.keepStancePrivate' | 'settings.showProfile' | 'settings.privacyInfo' | 'settings.aboutBuild' | 'settings.backend' | 'settings.aiStatus' | 'settings.version' | 'settings.scoreDisclaimer' | 'settings.aiDefaults' | 'settings.aiDefaultsBody' | 'settings.preferredOpponent' | 'settings.askEveryTime' | 'settings.aiOpponent' | 'settings.personOpponent' | 'settings.aiFamily' | 'settings.modelQuality' | 'settings.responseLength' | 'settings.showModelDetails' | 'settings.modelDetailsHelp' | 'settings.resetAppearance' | 'settings.guide' | 'settings.saved' | 'settings.deleteConfirm' | 'settings.deleted' | 'settings.deleteError'
  | 'ai.connectionLive' | 'ai.connectionMock' | 'ai.connected' | 'ai.connecting' | 'ai.failed' | 'ai.notConnected' | 'ai.mockBody' | 'ai.liveBody' | 'ai.mockSmall' | 'ai.liveSmall' | 'ai.connectPuter' | 'ai.activateMock' | 'ai.setupEyebrow' | 'ai.setupTitle' | 'ai.setupBody' | 'ai.motion' | 'ai.privateMotion' | 'ai.privateMotionPlaceholder' | 'ai.motionHelp' | 'ai.opponents' | 'ai.pushBack' | 'ai.compatibleModel' | 'ai.connectToCheck' | 'ai.noCompatibleModel' | 'ai.quality' | 'ai.yourSide' | 'ai.difficulty' | 'ai.debateLength' | 'ai.responseLength' | 'ai.advanced' | 'ai.exactModel' | 'ai.start' | 'ai.exit' | 'ai.round' | 'ai.you' | 'ai.opponent' | 'ai.argumentPlaceholder' | 'ai.sendArgument' | 'ai.stop' | 'ai.retry' | 'ai.complete' | 'ai.completeBody' | 'ai.completeReview' | 'ai.reviewUnavailable' | 'ai.resultTitle' | 'ai.argumentReview' | 'ai.argumentDna' | 'ai.rematch' | 'ai.swap' | 'ai.changeOpponent' | 'ai.anotherTake'
  | 'ai.developmentReady' | 'ai.allowance' | 'ai.usageUnavailable' | 'ai.noAllowance' | 'ai.remaining' | 'ai.refreshAllowance' | 'ai.usageNotice' | 'ai.qualityFast' | 'ai.qualityFastBody' | 'ai.qualityBalanced' | 'ai.qualityBalancedBody' | 'ai.qualityMaximum' | 'ai.qualityMaximumBody' | 'ai.maximumNote' | 'ai.difficultyBeginner' | 'ai.difficultyIntermediate' | 'ai.difficultyAdvanced' | 'ai.difficultyExpert' | 'ai.roundQuick' | 'ai.roundStandard' | 'ai.roundDeep' | 'ai.rounds' | 'ai.responseConcise' | 'ai.responseConciseBody' | 'ai.responseStandard' | 'ai.responseStandardBody' | 'ai.responseDetailed' | 'ai.responseDetailedBody' | 'ai.advancedBody' | 'ai.automaticFallback' | 'ai.exactModelLabel' | 'ai.savedModelUnavailable' | 'ai.modelCatalogueSource' | 'ai.connectBeforeStart' | 'ai.allowanceExhausted' | 'ai.chooseAvailable' | 'ai.invalidMotion' | 'ai.startError' | 'ai.scoreWhy' | 'ai.scoreGrounding' | 'ai.unansweredPoint' | 'ai.concessionSignal' | 'ai.noConcession' | 'ai.improvement'
  | 'groups.eyebrow' | 'groups.title' | 'groups.body' | 'groups.create' | 'groups.private' | 'groups.name' | 'groups.description' | 'groups.rules' | 'groups.example' | 'groups.roomFor' | 'groups.rulesPlaceholder' | 'groups.pointsToggle' | 'groups.pointsHelp' | 'groups.createPrivate' | 'groups.haveInvite' | 'groups.joinRoom' | 'groups.inviteHelp' | 'groups.invitePlaceholder' | 'groups.joinGroup' | 'groups.loading' | 'groups.emptyTitle' | 'groups.emptyBody' | 'groups.backHome' | 'groups.inviteCode' | 'groups.createInvite' | 'groups.inviteCreated' | 'groups.inviteHelpDetail' | 'groups.topics' | 'groups.topicRoom' | 'groups.noTopics' | 'groups.suggestTopic' | 'groups.statement' | 'groups.context' | 'groups.supportLabel' | 'groups.questionLabel' | 'groups.sensitivity' | 'groups.sensitive' | 'groups.saveTopic' | 'groups.members' | 'groups.people' | 'groups.rulesTitle' | 'groups.leaderboard' | 'groups.pointsBody' | 'groups.membersCount' | 'groups.needsReview'
  | 'groups.backGroups' | 'groups.startTeam' | 'groups.copyInvite' | 'groups.debateTopic' | 'groups.privateRoomDescription' | 'groups.member' | 'groups.roleOwner' | 'groups.roleModerator' | 'groups.roleMember' | 'groups.points' | 'groups.constructivePoints' | 'groups.topicLengthError' | 'groups.createError' | 'groups.openError'
  | 'team.sharedDevice' | 'team.title' | 'team.body' | 'team.privateSession' | 'team.topicStep' | 'team.chooseMotion' | 'team.customTopic' | 'team.customTopicPlaceholder' | 'team.neutralContextPlaceholder' | 'team.customTopicHelp' | 'team.teamsStep' | 'team.buildRoom' | 'team.count' | 'team.quickStart' | 'team.pickStructure' | 'team.quickClassroom' | 'team.quickClassroomBody' | 'team.standardDebate' | 'team.standardDebateBody' | 'team.deepDebate' | 'team.deepDebateBody' | 'team.structureStep' | 'team.setPace' | 'team.roundMode' | 'team.timerMode' | 'team.rounds' | 'team.turnSeconds' | 'team.totalMinutes' | 'team.preparationSeconds' | 'team.roundTypes' | 'team.includeClosing' | 'team.shortDebates' | 'team.results' | 'team.summaryOnly' | 'team.facilitatorScoring' | 'team.aiFeedback' | 'team.textAvailable' | 'team.voiceOptional' | 'team.start' | 'team.starting' | 'team.exitSetup' | 'team.end' | 'team.current' | 'team.motion' | 'team.previousArgument' | 'team.answerPoint' | 'team.makeCase' | 'team.paused' | 'team.saveTurn' | 'team.submitTurn' | 'team.pauseTimer' | 'team.resumeTimer' | 'team.skipTeam' | 'team.facilitatorControls' | 'team.hideControls' | 'team.controlsHelp' | 'team.addSeconds' | 'team.privacyNote' | 'team.complete' | 'team.goodWork' | 'team.completeBody' | 'team.backToSetup' | 'team.turns' | 'team.teams' | 'team.aiAssisted' | 'team.techniqueNotIdeology' | 'team.reviewLoading' | 'team.reviewUnavailable' | 'team.strongestPoint' | 'team.openQuestion' | 'team.transcriptEvidence' | 'team.rubric' | 'team.facilitatorNote' | 'team.commonGround' | 'team.commonGroundPlaceholder' | 'team.savedNote' | 'team.sessionNote' | 'team.saveNote' | 'team.startAnother' | 'team.printTranscript' | 'team.noSubmittedTurns' | 'team.roundType.opening' | 'team.roundType.argument' | 'team.roundType.rebuttal' | 'team.roundType.question' | 'team.roundType.answer' | 'team.roundType.closing'
  | 'feedback.title' | 'feedback.body' | 'feedback.type' | 'feedback.shortNote' | 'feedback.placeholder' | 'feedback.thanks' | 'feedback.error'
  | 'friends.eyebrow' | 'friends.title' | 'friends.body' | 'friends.add' | 'friends.handle' | 'friends.code' | 'friends.lookup' | 'friends.lookupHint' | 'friends.request' | 'friends.incoming' | 'friends.sent' | 'friends.accept' | 'friends.decline' | 'friends.cancel' | 'friends.remove' | 'friends.block' | 'friends.unblock' | 'friends.blocked' | 'friends.empty' | 'friends.noResults' | 'friends.challenge' | 'friends.challengeMode' | 'friends.challengeArgument' | 'friends.challengePlaceholder' | 'friends.sendChallenge' | 'friends.challenges' | 'friends.answer' | 'friends.answerPlaceholder' | 'friends.submitAnswer' | 'friends.groupInvites' | 'friends.inviteToGroup' | 'friends.chooseGroup' | 'friends.acceptInvite' | 'friends.declineInvite' | 'friends.privateOnly' | 'friends.deviceOnly' | 'friends.unavailable' | 'friends.member' | 'friends.codeRegenerate' | 'friends.copyCode' | 'friends.photo' | 'friends.photoHelp' | 'friends.choosePhoto' | 'friends.takePhoto' | 'friends.previewPhoto' | 'friends.usePhoto' | 'friends.photoPermission' | 'friends.photoUnavailable' | 'friends.removePhoto' | 'friends.visibility' | 'friends.friendsOnly' | 'friends.sharedGroups' | 'friends.private' | 'friends.stats' | 'friends.statDebates' | 'friends.statSideSwitches' | 'friends.statConstructive' | 'friends.statArgumentDna'
  | 'status.connecting' | 'status.privateSession' | 'status.privateUnavailable' | 'status.backendUnavailable' | 'status.loadingSpace' | 'status.backendMessage' | 'status.retryConnection' | 'status.retrySession'
  | `classic.${string}` | `results.${string}` | `clash.${string}` | `ai.${string}` | `ai.active.${string}` | `onboarding.${string}`

export type LocaleMessages = Record<TranslationKey, string>
export type Translator = (key: TranslationKey, values?: Record<string, string | number>) => string

export const supportedLanguages: readonly Language[] = ['en', 'de', 'fr', 'es', 'it']
