import { useEffect, useMemo, useState } from 'react'
import { Button, Icon, Tag } from '../../components/SideShiftUI'
import type { Language } from '../../domain'
import { formatDate, useTranslations, type TranslationKey } from '../../i18n'
import type { AppRepository, LeagueDashboard } from '../../data/repository'

type Props = { userId: string; language: Language; repository: AppRepository; leagueType: 'friends' | 'group'; groupId?: string | null }
const reasonKey: Record<string, TranslationKey> = { completed_debate: 'league.completedDebate', sideswitch: 'league.sideSwitch', topic_variety: 'league.topicVariety', friend_challenge: 'league.friendChallenge', team_debate: 'league.teamDebate', constructive_completion: 'league.constructive', weekly_consistency: 'league.consistency' }
const awardKey: Record<string, TranslationKey> = { 'Most Improved': 'league.mostImproved', 'Best Rebuttal': 'league.bestRebuttal', 'Best Listener': 'league.bestListener', 'SideSwitch Specialist': 'league.sideSwitchSpecialist', 'Topic Explorer': 'league.topicExplorer', 'Most Consistent': 'league.mostConsistent', 'Team Contributor': 'league.teamContributor' }

export function LeaguePanel({ userId, language, repository, leagueType, groupId = null }: Props) {
  const t = useTranslations(language)
  const [dashboard, setDashboard] = useState<LeagueDashboard | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const title = leagueType === 'friends' ? t('league.friends') : t('league.group')
  async function load() { try { setError(''); setDashboard(await repository.loadLeagueDashboard(userId, leagueType, groupId)) } catch (caught) { setError(caught instanceof Error ? caught.message : t('league.error')) } }
  useEffect(() => { void load() }, [groupId, leagueType, repository, userId])
  async function toggle() { setBusy(true); try { if (dashboard?.joined) await repository.leaveLeague(userId, leagueType, groupId); else if (leagueType === 'friends') await repository.joinFriendsLeague(userId); else if (groupId) await repository.joinGroupLeague(userId, groupId); await load() } catch (caught) { setError(caught instanceof Error ? caught.message : t('league.error')) } finally { setBusy(false) } }
  const own = dashboard?.participants.find(item => item.userId === userId)
  const position = dashboard?.participants.findIndex(item => item.userId === userId)
  const breakdown = useMemo(() => dashboard?.myEvents.slice(0, 8) || [], [dashboard])
  return <section className="league-panel card-surface" aria-labelledby={`league-${leagueType}`}><div className="section-heading"><div><span className="eyebrow">{t('league.title')}</span><h2 id={`league-${leagueType}`}>{title}</h2><p className="muted">{t('league.body')}</p></div><Tag tone="lavender"><Icon name="lock" size={13} /> {t('league.privateOnly')}</Tag></div>{error && <p className="form-error" role="alert">{error}</p>}{!dashboard ? <p className="muted">{t('league.loading')}</p> : !dashboard.available ? <p className="muted">{t('league.error')}</p> : <>{dashboard.season && <div className="league-season-meta"><span><strong>{t('league.season')}</strong> {formatDate(dashboard.season.startAt, language)} — {formatDate(dashboard.season.endAt, language)}</span>{dashboard.joined && own && <span><strong>{own.points}</strong> {t('league.points')} · {t('league.position')} {(position ?? 0) + 1}</span>}</div>}<p className="field-help">{dashboard.joined ? t('league.joined') : t('league.notJoined')}</p><Button variant={dashboard.joined ? 'secondary' : 'dark'} onClick={() => void toggle()} disabled={busy || (leagueType === 'group' && !groupId)}>{busy ? t('common.saving') : dashboard.joined ? t('league.leave') : t('league.join')}</Button>{dashboard.joined && <><div className="league-standings"><div className="settings-section-heading"><h3>{t('league.standings')}</h3></div>{dashboard.participants.length ? dashboard.participants.slice(0, 12).map((participant, index) => <div className="leaderboard-row" key={participant.userId}><b aria-label={`${t('league.position')} ${index + 1}`}>{index + 1}</b><span>{participant.userId === userId ? `${participant.displayName} · ${t('league.you')}` : participant.displayName === 'Member' ? t('league.member') : participant.displayName}</span><strong>{participant.points} {t('league.points')}</strong></div>) : <p className="muted">{t('league.noParticipants')}</p>}</div><div className="league-breakdown"><div className="settings-section-heading"><h3>{t('league.breakdown')}</h3></div>{breakdown.length ? breakdown.map(event => <div className="league-event-row" key={event.id}><span>{t(reasonKey[event.reason] || 'league.completedDebate')}</span><strong>+{event.points}</strong><small>{event.category} · {formatDate(event.occurredAt, language)}</small></div>) : <p className="muted">{t('league.noActivity')}</p>}</div>{dashboard.awards.length > 0 && <div className="league-awards"><div className="settings-section-heading"><h3>{t('league.awards')}</h3></div>{dashboard.awards.map(award => <Tag tone="yellow" key={`${award.userId}-${award.award}`}>{t(awardKey[award.award] || 'league.award')}</Tag>)}</div>}</>}</>}</section>
}
