import { useEffect, useMemo, useState } from 'react'
import { Button, Icon, Tag } from '../../components/SideShiftUI'
import { formatDate, localizeInterest, useTranslations } from '../../i18n'
import type { Language, Take } from '../../domain'
import { buildWorldPulseTake, type WorldPulseItem } from '../../worldPulse'
import { openExternalUrl } from '../../capacitor'

type Props = { language: Language; items: WorldPulseItem[]; loading?: boolean; error?: boolean; hideSensitiveDefault?: boolean; onHideSensitiveChange?: (value: boolean) => void; onChooseDebate: (take: Take) => void }

export function WorldPulsePanel({ language, items, loading = false, error = false, hideSensitiveDefault = false, onHideSensitiveChange, onChooseDebate }: Props) {
  const t = useTranslations(language)
  const [region, setRegion] = useState('all')
  const [category, setCategory] = useState('all')
  const [sort, setSort] = useState<'newest' | 'expiring' | 'historical'>('newest')
  const [hideSensitive, setHideSensitive] = useState(hideSensitiveDefault)
  const [openSources, setOpenSources] = useState<string | null>(null)
  const [pendingSensitive, setPendingSensitive] = useState<WorldPulseItem | null>(null)
  const categories = useMemo(() => [...new Set(items.map(item => item.category))], [items])
  useEffect(() => { setHideSensitive(hideSensitiveDefault) }, [hideSensitiveDefault])
  const filtered = items.filter(item => (!hideSensitive || item.sensitivity === 'standard') && (region === 'all' || item.region === region) && (category === 'all' || item.category === category)).sort((a, b) => {
    if (sort === 'expiring') return (Date.parse(a.expiresAt || '9999-12-31') || Number.MAX_SAFE_INTEGER) - (Date.parse(b.expiresAt || '9999-12-31') || Number.MAX_SAFE_INTEGER)
    if (sort === 'historical') return (Date.parse(a.eventDate || '9999-12-31') || Number.MAX_SAFE_INTEGER) - (Date.parse(b.eventDate || '9999-12-31') || Number.MAX_SAFE_INTEGER)
    return (Date.parse(b.publishAt || b.updatedAt) || 0) - (Date.parse(a.publishAt || a.updatedAt) || 0)
  })
  function start(item: WorldPulseItem) { if (item.sensitivity !== 'standard') setPendingSensitive(item); else onChooseDebate(buildWorldPulseTake(item, language)) }
  return <section className="world-pulse-section section-block" aria-labelledby="world-pulse-title">
    <div className="section-heading"><div><span className="eyebrow">{t('worldPulse.tab')}</span><h2 id="world-pulse-title">{t('worldPulse.title')}</h2><p className="muted">{t('worldPulse.body')}</p></div><Tag tone="mint"><Icon name="shield" size={13} /> {t('common.private')}</Tag></div>
    <div className="filter-row world-pulse-filters" role="group" aria-label={t('worldPulse.title')}><button type="button" className={region === 'all' ? 'filter active' : 'filter'} onClick={() => setRegion('all')}>{t('worldPulse.myRegion')}</button><button type="button" className={region === 'Europe' ? 'filter active' : 'filter'} onClick={() => setRegion('Europe')}>{t('worldPulse.europe')}</button><button type="button" className={region === 'World' ? 'filter active' : 'filter'} onClick={() => setRegion('World')}>{t('worldPulse.world')}</button><select className="settings-select compact-select" aria-label={t('worldPulse.category')} value={category} onChange={event => setCategory(event.target.value)}><option value="all">{t('worldPulse.category')}</option>{categories.map(value => <option value={value} key={value}>{localizeInterest(value, language)}</option>)}</select><select className="settings-select compact-select" aria-label={t('worldPulse.newest')} value={sort} onChange={event => setSort(event.target.value as typeof sort)}><option value="newest">{t('worldPulse.newest')}</option><option value="expiring">{t('worldPulse.expiring')}</option><option value="historical">{t('worldPulse.historical')}</option></select><label className="toggle-row inline-toggle"><input type="checkbox" checked={hideSensitive} onChange={event => { setHideSensitive(event.target.checked); onHideSensitiveChange?.(event.target.checked) }} /><span>{t('worldPulse.hideSensitive')}</span></label></div>
    {loading ? <p className="empty-state card-surface">{t('worldPulse.loading')}</p> : error ? <p className="empty-state card-surface" role="alert">{t('worldPulse.error')}</p> : filtered.length === 0 ? <p className="empty-state card-surface">{t('worldPulse.noItems')}</p> : <div className="world-pulse-grid">{filtered.map(item => <article className="world-pulse-card card-surface" key={item.id}><div className="card-topline"><Tag tone={item.sensitivity === 'standard' ? 'coral' : 'yellow'}>{item.sensitivity === 'standard' ? localizeInterest(item.category, language) : t('worldPulse.sensitive')}</Tag><span className="card-date"><Icon name="globe" size={14} /> {item.region || t('worldPulse.world')}</span></div><h3>{item.debateStatement}</h3><p className="world-pulse-why"><strong>{t('worldPulse.whyNow')}</strong> {item.neutralContext}</p><div className="world-pulse-meta"><span>{t('worldPulse.reviewed')}: {formatDate(item.lastReviewedAt, language)}</span><span>{t('worldPulse.sources', { count: item.sourceCount })}</span></div><div className="world-pulse-actions"><Button variant="dark" onClick={() => start(item)}>{t('worldPulse.start')}</Button><button type="button" className="text-link" onClick={() => setOpenSources(openSources === item.id ? null : item.id)} aria-expanded={openSources === item.id}>{t('worldPulse.sourcePanel')}</button></div>{openSources === item.id && <div className="world-pulse-sources"><strong>{t('worldPulse.sourcePanel')}</strong>{item.sources.map(source => <a href={source.url} target="_blank" rel="noopener noreferrer" key={source.url} onClick={event => { event.preventDefault(); void openExternalUrl(source.url) }}>{source.publisher}: {source.title}<Icon name="link" size={13} /></a>)}</div>}</article>)}</div>}
    {pendingSensitive && <div className="modal-scrim"><section className="modal-card card-surface" role="dialog" aria-modal="true" aria-labelledby="world-pulse-warning"><button type="button" className="modal-close" onClick={() => setPendingSensitive(null)} aria-label={t('common.close')}><Icon name="close" size={18} /></button><Tag tone="yellow">{t('worldPulse.sensitive')}</Tag><h2 id="world-pulse-warning">{t('worldPulse.sensitive')}</h2><p>{t('worldPulse.sensitiveBody')}</p><div className="modal-actions"><Button variant="dark" onClick={() => { const next = pendingSensitive; setPendingSensitive(null); onChooseDebate(buildWorldPulseTake(next, language)) }}>{t('worldPulse.start')}</Button><button type="button" className="button button-ghost" onClick={() => setPendingSensitive(null)}>{t('common.cancel')}</button></div></section></div>}
  </section>
}
